export enum Configuration {
	PORT = 'PORT',
	HOST = 'HOST',
	DB_USERNAME = 'DB_USERNAME',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_NAME = 'DB_NAME',
	DB_PORT = 'DB_PORT',
	DB_TYPE = 'DB_TYPE',
	HASH_KEY = 'HASH_KEY',
}
