export enum Configuration {
	PORT = 'PORT',
	HOST = 'HOST',
	PGUSER = 'PGUSER',
	PGDATABASE = 'PGDATABASE',
	DB_PASSWORD = 'DB_PASSWORD',
	DB_PORT = 'DB_PORT',
	DB_TYPE = 'DB_TYPE',
	HASH_KEY = 'HASH_KEY',
}
